// Generated by CoffeeScript 1.4.0
(function() {
  var input, midi, midi_port, sock, trTable, zmq,
    _this = this;

  module.exports = function() {};

  trTable = {
    48: [0, "/", "first"],
    47: [0, "/afdb-load", "second"]
  };

  midi = require("midi");

  zmq = require("zmq");

  midi_port = 1;

  input = new midi.input();

  console.log("Using port " + (input.getPortName(midi_port)));

  sock = zmq.socket('push');

  sock.bind('tcp://127.0.0.1:43000');

  input.on("message", function(deltaTime, message) {
    var func, missile, note, vel;
    func = message[0], note = message[1], vel = message[2];
    if (func === 153) {
      console.log("note: " + note + " vel: " + vel);
      if (note in trTable) {
        missile = trTable[note];
        console.log("Sending (" + missile + ")");
        sock.send(JSON.stringify(missile));
      }
    }
  });

  input.openPort(midi_port);

  input.ignoreTypes(false, false, false);

  console.log('Listening for MIDI messages. Press any key to exit');

  process.stdin.setRawMode(true);

  process.stdin.resume();

  process.stdin.on('data', function() {
    input.closePort();
    return process.exit();
  });

}).call(this);
